config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'
  
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'  
  resources :sessions

  resources :fruitsales
  resources :products
  resources :promotions
  get 'report/reportlist'

  get 'report/customerlist'

  get 'report/productlist'

  get 'report/salelist'

  get 'report/customerlist'

  resources :sales
  resources :suppliers
  resources :customers
  get 'home/about'

  get 'home/contact'
 
  get 'home/index'
  
  get 'home/privacy'
  
  get 'home/help'
  
  get 'home/cart'
  get 'cart', to: 'home#cart', as: 'cart'
  
  get 'home/catalog'
  post 'home/buy'
  post 'home/updatecart'
  post 'home/checkout'
  
  get 'products/show'
  get 'suppliers/show'
  
  get "home/search"
  post "home/search"

  root 'home#index'

end

app/models/fruitsale.rb
class Fruitsale < ActiveRecord::Base
    belongs_to :customer
    belongs_to :product 
end

app/controllers/fruitsales_controller.rb
class FruitsalesController < ApplicationController
  before_action :set_fruitsale, only: [:show, :edit, :update, :destroy]

  # GET /fruitsales
  # GET /fruitsales.json
  def index
    @fruitsales = Fruitsale.all
  end

  # GET /fruitsales/1
  # GET /fruitsales/1.json
  def show
  end

  # GET /fruitsales/new
  def new
    @fruitsale = Fruitsale.new
  end

  # GET /fruitsales/1/edit
  def edit
  end

  # POST /fruitsales
  # POST /fruitsales.json
  def create
    @fruitsale = Fruitsale.new(fruitsale_params)

    respond_to do |format|
      if @fruitsale.save
        format.html { redirect_to @fruitsale, notice: 'Fruitsale was successfully created.' }
        format.json { render :show, status: :created, location: @fruitsale }
      else
        format.html { render :new }
        format.json { render json: @fruitsale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fruitsales/1
  # PATCH/PUT /fruitsales/1.json
  def update
    respond_to do |format|
      if @fruitsale.update(fruitsale_params)
        format.html { redirect_to @fruitsale, notice: 'Fruitsale was successfully updated.' }
        format.json { render :show, status: :ok, location: @fruitsale }
      else
        format.html { render :edit }
        format.json { render json: @fruitsale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fruitsales/1
  # DELETE /fruitsales/1.json
  def destroy
    @fruitsale.destroy
    respond_to do |format|
      format.html { redirect_to fruitsales_url, notice: 'Fruitsale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fruitsale
      @fruitsale = Fruitsale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fruitsale_params
      params.require(:fruitsale).permit(:customer_id, :fruit_id, :saleprice, :purchasedate, :status, :purchase_id, :created_at, :updated_at)
    end
end

app/helpers/fruitsales_helper.rb
module FruitsalesHelper
end

app/views/fruitsales/_form.html.erb
<%= form_for(@fruitsale) do |f| %>
  <% if @fruitsale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fruitsale.errors.count, "error") %> prohibited this fruitsale from being saved:</h2>

      <ul>
      <% @fruitsale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :fruit_id %><br>
    <%= f.number_field :fruit_id %>
  </div>
  <div class="field">
    <%= f.label :saleprice %><br>
    <%= f.number_field :saleprice %>
  </div>
  <div class="field">
    <%= f.label :purchasedate %><br>
    <%= f.date_select :purchasedate %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :purchase_id %><br>
    <%= f.number_field :purchase_id %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br>
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fruitsales/edit.html.erb
<h1>Editing Fruitsale</h1>

<%= render 'form' %>

<%= link_to 'Show', @fruitsale %> |
<%= link_to 'Back', fruitsales_path %>

app/views/fruitsales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fruitsales</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Fruit</th>
      <th>Saleprice</th>
      <th>Purchasedate</th>
      <th>Status</th>
      <th>Purchase</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fruitsales.each do |fruitsale| %>
      <tr>
        <td><%= fruitsale.customer_id %></td>
        <td><%= fruitsale.fruit_id %></td>
        <td><%= fruitsale.saleprice %></td>
        <td><%= fruitsale.purchasedate %></td>
        <td><%= fruitsale.status %></td>
        <td><%= fruitsale.purchase_id %></td>
        <td><%= fruitsale.created_at %></td>
        <td><%= fruitsale.updated_at %></td>
        <td><%= link_to 'Show', fruitsale %></td>
        <td><%= link_to 'Edit', edit_fruitsale_path(fruitsale) %></td>
        <td><%= link_to 'Destroy', fruitsale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fruitsale', new_fruitsale_path %>

app/views/fruitsales/new.html.erb
<h1>New Fruitsale</h1>

<%= render 'form' %>

<%= link_to 'Back', fruitsales_path %>

app/views/fruitsales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @fruitsale.customer_id %>
</p>

<p>
  <strong>Fruit:</strong>
  <%= @fruitsale.fruit_id %>
</p>

<p>
  <strong>Saleprice:</strong>
  <%= @fruitsale.saleprice %>
</p>

<p>
  <strong>Purchasedate:</strong>
  <%= @fruitsale.purchasedate %>
</p>

<p>
  <strong>Status:</strong>
  <%= @fruitsale.status %>
</p>

<p>
  <strong>Purchase:</strong>
  <%= @fruitsale.purchase_id %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @fruitsale.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @fruitsale.updated_at %>
</p>

<%= link_to 'Edit', edit_fruitsale_path(@fruitsale) %> |
<%= link_to 'Back', fruitsales_path %>