config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'
  
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'  
  resources :sessions

  resources :fruitsales
  resources :products
  resources :promotions
  get 'report/reportlist'

  get 'report/customerlist'

  get 'report/productlist'

  get 'report/salelist'

  get 'report/customerlist'

  resources :sales
  resources :suppliers
  resources :customers
  get 'home/about'

  get 'home/contact'
 
  get 'home/index'
  
  get 'home/privacy'
  
  get 'home/help'
  
  get 'home/cart'
  get 'cart', to: 'home#cart', as: 'cart'
  
  get 'home/catalog'
  post 'home/buy'
  post 'home/updatecart'
  post 'home/checkout'
  
  get 'products/show'
  get 'suppliers/show'
  
  get "home/search"
  post "home/search"

  root 'home#index'

end

app/views/layouts/_footer.html.erb
<%= link_to "Contact Us", home_contact_path %>
<%= link_to "Privacy", home_privacy_path %>
<%= link_to "Help", home_help_path %> 

app/views/layouts/_header.html.erb
<table bgcolor='cornsilk' width="100%"> <tr>
    <td align='left'> <%= link_to (image_tag 'fruitlogo.png', size:"70x70" ), home_index_path%></td>
    <td align='left'> <h1>Brandon's Fruit Stand</h1></td>
    
    <td width='35%' align='right'>
        <%= form_tag :action => 'search', :controller => 'home' do %>
            <p> Search
            <%= text_field_tag 'searchinput', @searchinput %> 
            <%= submit_tag 'Go' %> </p>
        <% end %>
    </td>
    <td width='15%' align='center'>
		<% if session[:user_id].nil? %>
			<%= link_to "New Customer", new_customer_path %>
			<%= button_to 'Login', login_path, :method => :get %>
		<% else %>
			Hello <%= Customer.find(session[:user_id]).firstname %> !
			<%= button_to 'Logout', logout_path, :method => :delete %>
		<% end %>
		<p><%= link_to (image_tag "cart.png", size:"50x50"), home_cart_path %></p>
        </td>
    </tr></table>
<ul>
    <li><%= link_to "Home", home_index_path %></li>
    <li><%= link_to "About Us", home_about_path %></li>
    <li> <%= link_to "Store", products_path %></li>
    <li> <%= link_to "Our Suppliers", suppliers_path %> </li>
    <li><%= link_to "Reports", report_reportlist_path%></li>
    <li><%= link_to "Promotions", promotions_path %></li>
<li> </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brandon's Fruit Stand</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<body bgcolor ='lightgray'>
<center>
<table bgcolor='white' width='90%'>
  <tr><td><%= render "layouts/header" %></td></tr>
  <tr><td height='300' valign='top'><%= yield %></td></tr>
  <tr><td><%= render "layouts/footer" %></td> </tr>
  </table>
  </center>

</body>
</html>